### ISSUE TITLE
TensorflowHelper Documentation

### ISSUE THREAD

**Issue by pinduzera** [sassoftware/python-esppy#17]
How does the TensorflowHelper works on ESP?
This option doesn't seem to exist on the GUI, it has a small comment on ESP documentation and nothing but the function's documentation here https://sassoftware.github.io/python-esppy/generated/esppy.windows.pythonmas.TensorflowHelper.html?highlight=tensorflow#esppy.windows.pythonmas.TensorflowHelper

It transform an tensorflow model to SAS through ONNX or what happens exactly? Which are the limitations?

**Comment by yezmao-sas** [comment]
Hi, thanks for your message!

The TensorflowHelper actually help to load your tf model to the CalculateWindow. Here we have an [(example)](https://github.com/sassoftware/python-esppy/blob/master/examples/Tensorflow/demo-Tensorflow.ipynb) to show how it works in SAS ESP, hope it help!

Thanks,
Ye

**Comment by yezmao-sas** [comment]
> How does the TensorflowHelper works on ESP?
> This option doesn't seem to exist on the GUI, it has a small comment on ESP documentation and nothing but the function's documentation here https://sassoftware.github.io/python-esppy/generated/esppy.windows.pythonmas.TensorflowHelper.html?highlight=tensorflow#esppy.windows.pythonmas.TensorflowHelper
> 
> It transform an tensorflow model to SAS through ONNX or what happens exactly? Which are the limitations?

Hi, thanks for your message!

The TensorflowHelper actually help to load your tf model to the CalculateWindow. Here we have an [example](https://github.com/sassoftware/python-esppy/blob/master/examples/Tensorflow/demo-Tensorflow.ipynb) to show how it works in SAS ESP, hope it help!

Thanks,
Ye
